# Generated by Django 4.2.11 on 2026-07-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porterprofile',
            name='assigned_farmers',
            field=models.ManyToManyField(blank=True, related_name='assigned_porters', to='core.farmerprofile'),
        ),
    ]
