# Generated by Django 4.2.11 on 2026-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_porterprofile_assigned_farmers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
