# Generated by Django 4.2.11 on 2026-07-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_farmerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='porterprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
