# Generated by Django 4.2 on 2026-07-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_porterprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('porter', 'Porter'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
